# Generated by Django 4.1.7 on 2023-04-04 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0003_rename_trait_name_trait_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="name",
            new_name="trait_name",
        ),
    ]
