# Generated by Django 4.1.7 on 2023-04-04 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_rename_name_trait_trait_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="trait_name",
            new_name="name",
        ),
    ]
